name: Prerelease (next)

on:
  workflow_dispatch:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_PAT }}

      - name: Set up Git user
        run: |
          git config --global user.email "info@navigraph.com"
          git config --global user.name "Navigraph Bot"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build packages
        run: yarn build

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci(changesets): version packages [no ci]"
          title: "ci(changesets, prerelease): version packages"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to @next-dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          yarn changeset version --snapshot next
          yarn changeset publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
